construction_code_mapping_dict = {'RMS1':'Wood',
'RMS1A':'Light Wood',
'RMS1A1':'Light Wood Stud Walls',
'RMS1A2':'Light Wood Post & Beam',
'RMS1B':'Heavy Timber',
'RMS1B1':'Heavy Timber Frame',
'RMS1B2':'Heavy Timber URM infill',
'RMS2':'Masonry',
'RMS2A':'Weak Masonry',
'RMS2A1':'Rubble Stone Masonry',
'RMS2A2':'Adobe',
'RMS2B':'Unreinforced Masonry (URM)',
'RMS2B1':'Unreinforced Cut Stone Masonry',
'RMS2B2':'Unreinforced Solid Brick Masonry',
'RMS2B3':'Unreinforced Concrete Block Masonry',
'RMS2C':'Structural Masonry',
'RMS2C1':'Reinforced Masonry Sheer Wall',
'RMS2C2':'Confined Masonry',
'RMS3':'Reinforced Concrete',
'RMS3A':'Cast-in-place RC',
'RMS3A1':'RC MRF',
'RMS3A2':'RC Moment Resisting Frame with Sheer Walls',
'RMS3A3':'RC Moment Resiting Frame with URM',
'RMS3A4':'RC Shear Wall',
'RMS3A5':'Waffle or Flat Slab',
'RMS3A6':'Steel & RC Composite Frame',
'RMS3A7':'Concrete Piloti',
'RMS3A8':'CFT',
'RMS3A9':'Gravity Load Designed RC with Unreinforced Masonry',
'RMS3A10':'RC Frame',
'RMS3B':'Precast Concrete',
'RMS3B1':'Precast MRF',
'RMS3B2':'Precast MRF with Shear Walls',
'RMS3B3':'Precast MRF (URM)',
'RMS3B4':'Tilt-Up',
'RMS3B5':'Precast Panel Bearing Walls',
'RMS3B6':'Lift Slab',
'RMS3C':'RC with Wood and Light Metal',
'RMS4':'Steel',
'RMS4A':'Steel Frame',
'RMS4A1':'Steel MRF',
'RMS4A2':'Steel MRF with Shear Walls',
'RMS4A3':'Steel MRF (URM)',
'RMS4A4':'Concentrically Braced Steel Frame',
'RMS4A5':'Eccentrically Braced Steel Frame',
'RMS4A6':'Gravity Load Designed Steel (URM)',
'RMS4A7':'Steel Frame with Wood Frame',
'RMS4B':'Light Metal Frame',
'RMS4B1':'Light Metal Frame',
'RMS4B2':'Light Metal Frame (URM)',
'RMS5':'Manufactured/Mobile Home',
'RMS5A':'Manufactured/Mobiled Home without Tie-Downs',
'RMS5B':'Manufactured/Mobile Home with Tie-Downs',
'RMS6':'Conventional Bridges (<500 ft. spans)',
'RMS7':'Conventional Bridges (<500 ft. spans)',
'RMS8':'Major Bridges (>500 ft. spans)',
'RMS9':'Underground Pipelines',
'RMS10':'Pipelines at Grade',
'RMS11':'Concrete Dams',
'RMS12':'Earthfill and Rockfill Dams',
'RMS13':'Alluvium Tunnels',
'RMS14':'Rock Tunnels',
'RMS15':'Cut & Cover Tunnels',
'RMS16':'Underground Liquid Storage Tanks',
'RMS17':'Underground Solid Storage Tanks',
'RMS18':'On Ground Liquid Storage Tanks',
'RMS19':'On Ground Solid Storage Tanks',
'RMS20':'Elevated Liquid Storage Tanks',
'RMS21':'Elevated Solid Storage Tanks',
'RMS22':'Railroads (Track & Bed)',
'RMS23':'Highways',
'RMS24':'Runways',
'RMS25':'High Industrial Masonry Chimneys',
'RMS26':'High Indsutrial Concrete Chimneys',
'RMS27':'High Industrial Steel Chimneys',
'RMS28':'Cranes',
'RMS29':'Conveyor Systems',
'RMS30':'Conventional (<100 ft.) Electrical Transmission Line Towers',
'RMS31':'Manjor (>100 ft) Electrical Transmission Line Towers',
'RMS32':'Broadcast Towers',
'RMS33':'Observation Towers',
'RMS34':'Offshore Towers',
'RMS35':'Canals',
'RMS36':'Earth Retaining Structures (>20 ft high)',
'RMS37':'Waterfront Structures',
'RMS38':'Residential Equipment',
'RMS39':'Office Equipment',
'RMS40':'Electrical Equipment',
'RMS41':'Mechanical Equipment',
'RMS42':'High Technology/Lab Equipment',
'RMS43':'Trains, Trucks, Airplanes',
'RMS44':'Automobile - Personal',
'RMS45':'Automobile - Dealers',
'RMS46':'Petrochemical Facilities',
'RMS46A':'Oil Refineries & Petrochemical Plants',
'RMS46B':'Tanks Farms',
'RMS46C':'Pumping Stations',
'RMS46D':'Pipelines',
'RMS47':'Electric Power Systems',
'RMS47A':'Transmission/Distribution Substations',
'RMS47B':'Transmission/Distribution Lines',
'RMS47C':'Fossil Fuel Plants',
'RMS47D':'Cogeneration Plants',
'RMS47E':'Hydroelectric Plants',
'RMS48':'Natural Gas Facilitties',
'RMS48A':'Compressor Stations',
'RMS48B':'Pipelines',
'RMS48C':'Liquified Natural Gas',
'RMS49':'Port/Harbor Facilities',
'RMS49A':'Waterfront Facilities',
'RMS49B':'Crane/Cargo Handling',
'RMS49C':'Fuel Facilities',
'RMS50':'Heavy Industrial Facilities',
'RMS50A':'Pulp & Paper',
'RMS50B':'Steel Mill',
'RMS50C':'Mining',
'RMS50D':'Cement Mill',
'RMS51':'Light Industrial Facilities',
'RMS51A':'High Technology',
'RMS51B':'Telecommunication',
'RMS52':'MIXED (Greece only)',
'RMS52A':'Wood Frame Single Wall (Hawaii only)',
'RMS52B':'Wood Frame Double Wall (Hawaii only)',
'RMS53':'Golf Country Club',
'RMS54':'Boats, Inside a Building (Marina)',
'RMS55':'Boats, Moored, Less than 26ft, Motor',
'RMS56':'Boats, Moored, Less than 26ft, Sail',
'RMS57':'Boats, Moored, 26-60 ft, Motor',
'RMS58':'Boats, Moored, 26-60 ft, Sail',
'RMS59':'Boats, Moored, Greater than 60 ft, Motor',
'RMS60':'Boats, Mored, Greater than 60 ft, Sail',
'RMS61':'Floating Structures',
'RMS62':'Response Control System - General',
'RMS62A':'Response Control System - Concrete',
'RMS62B':'Response Control System - Steel',
'RMS63':'Aircraft, Small (NAHU only)',
'RMS64':'Aircraft, Medium (NAHU only)',
'RMS65':'Aircraft, Large (NAHU only)',
'RMS IND1':'Light Metal',
'RMS IND2':'Unreinforced Masonry Wall',
'RMS IND3':'Reinforced Concrete',
'RMS IND4':'Nonductile Concrete',
'RMS IND5':'Reinforced Masonry',
'RMS IND6':'Steel Frame',
'RMS IND7':'Tilt-Up',
'FIRE1':'Frame',
'FIRE2':'Joisted Masonry',
'FIRE3':'Non-Combustible',
'FIRE4':'Masonry Non-Combustible',
'FIRE5':'Modified Fire Resistive',
'FIRE6':'Fire Resistive',
'ATC1':'Wood Frame',
'ATC2':'Light Metal',
'ATC3':'Unreinforced Masonry Wall',
'ATC4':'URM Wall with Frame',
'ATC5':'RC Shear Wall with Frame',
'ATC6':'RC Shear Wall without Frame',
'ATC7':'RM Shear Wall',
'ATC8':'RM Shear Wall with Frame',
'ATC9':'Braced Steel Frame',
'ATC10':'Moment Steel Frame (Perimeter)',
'ATC11':'Moment Steel Frame (Distributed)',
'ATC12':'Ductile RC Frame (Distributed)',
'ATC13':'Non-Ductile RC Frame (Distributed)',
'ATC14':'Precast Concrete (Non Tilt-Up)',
'ATC15':'Long Span',
'ATC16':'Tilt-Up',
'ATC17':'Mobile Home',
'ATC18':'Specially Engineered Facility',
'ATC80':'Reinforced Concrete Frame with Wood Frame in the Upper Floors',
'FIRE1':'Frame',
'FIRE2':'Joisted Masonry',
'FIRE3':'Non-Combustible',
'FIRE4':'Masonry Non-Combustible',
'FIRE5':'Modified Fire Resistive',
'FIRE6':'Fire Resistive',
'FIRE7':'Heavy Timber Joisted Masonry',
'FIRE8':'Superior Non-Combustible',
'FIRE9':'Superior Masonry Non-Combustible',
'FIRE10':'Conventional Bridges (< 500 ft. spans) w/ Multiple Simple Spans',
'FIRE11':'Conventional Bridges (< 500 ft. spans) w/ Monolithic Spans',
'FIRE12':'Major Bridges (> 500 ft. spans)',
'FIRE13':'Underground Pipelines',
'FIRE14':'Pipelines At Grade',
'FIRE15':'Concrete Dams',
'FIRE16':'Earthfill and Rockfill Dams',
'FIRE17':'Alluvium Tunnels',
'FIRE18':'Rock Tunnels',
'FIRE19':'Cut & Cover Tunnels',
'FIRE20':'Underground Liquid Storage Tanks',
'FIRE21':'Underground Solid Storage Tanks',
'FIRE22':'On Ground Liquid Storage Tanks',
'FIRE23':'On Ground Solid Storage Tanks',
'FIRE24':'Elevated Liquid Storage Tanks',
'FIRE25':'Elevated Solid Storage Tanks',
'FIRE26':'Railroads (Track & Bed)',
'FIRE27':'Highways',
'FIRE28':'Runways',
'FIRE29':'High Industrial Masonry Chimneys',
'FIRE30':'High Industrial Concrete Chimneys',
'FIRE31':'High Industrial Steel Chimneys',
'FIRE32':'Cranes',
'FIRE33':'Conveyor Systems',
'FIRE34':'Conventional (< 100 ft.) Electrical Transmission Line Towers',
'FIRE35':'Major (> 100 ft.) Electrical Transmission Line Towers',
'FIRE36':'Broadcast Towers',
'FIRE37':'Observation Towers',
'FIRE38':'Offshore Towers',
'FIRE39':'Canals',
'FIRE40':'Earth Retaining Structures (> 20 ft. high)',
'FIRE41':'Waterfront Structures',
'FIRE42':'Residential Equipment',
'FIRE43':'Office Equipment',
'FIRE44':'Electrical Equipment',
'FIRE45':'Mechanical Equipment',
'FIRE46':'High Technology/Lab Equipment',
'FIRE47':'Trains, Trucks, Airplanes',
'FIRE48A':'Oil Refineries & Petrochemical Plants',
'FIRE48B':'Tank Farms',
'FIRE48C':'Pumping Stations',
'FIRE48D':'Pipelines',
'FIRE49A':'Transmission/Distribution Substations',
'FIRE49B':'Transmission/Distribution Lines',
'FIRE49C':'Fossil Fuel Plants',
'FIRE49D':'Cogeneration Plants',
'FIRE49E':'Hydroelectric Plants',
'FIRE50A':'Compressor Stations',
'FIRE50B':'Pipelines',
'FIRE50C':'Liquefied Natural Gas',
'FIRE51A':'Waterfront Facilities',
'FIRE51B':'Crane/Cargo Handling',
'FIRE51C':'Fuel Facilities',
'FIRE52A':'Pulp & Paper',
'FIRE52B':'Steel Mill',
'FIRE52C':'Mining',
'FIRE52D':'Cement Mill',
'FIRE53A':'High Technology',
'FIRE53B':'Telecommunication',
'ISO1':'Wood Frame - Small',
'ISO2':'Wood Frame - Large',
'ISO3':'Metal Building - Small',
'ISO4':'Metal Building - Large',
'ISO5':'Steel Frame - Superior',
'ISO6':'Steel Frame - Ordinary',
'ISO7':'Steel Frame - Other',
'ISO8':'Reinforced Concrete - Superior',
'ISO9':'Reinforced Concrete - Ordinary',
'ISO10':'Reinforced Concrete - Precast',
'ISO11':'Reinforced Concrete - Other',
'ISO12':'Mixed Construction - Superior',
'ISO13':'Mixed Construction - Ordinary EQ Resistive',
'ISO14':'Mixed Construction - Ordinary Non-EQ Resistive',
'ISO15':'Mixed Construction - Hollow Masonry & Adobe',
'ISO16':'Earthquake Resistive',
'ISO17':'Habitational - Mobile Homes',
'ISO18':'Specially Engineered Facility',
'ISO19':'Conventional Bridges (< 500 ft. spans) w/ Multiple Simple Spans',
'ISO20':'Conventional Bridges (< 500 ft. spans) w/ Monolithic Spans',
'ISO21':'Major Bridges (> 500 ft. spans)',
'ISO22':'Underground Pipelines',
'ISO23':'Pipelines At Grade',
'ISO24':'Concrete Dams',
'ISO25':'Earthfill and Rockfill Dams',
'ISO26':'Alluvium Tunnels',
'ISO27':'Rock Tunnels',
'ISO28':'Cut & Cover Tunnels',
'ISO29':'Underground Liquid Storage Tanks',
'ISO30':'Underground Solid Storage Tanks',
'ISO31':'On Ground Liquid Storage Tanks',
'ISO32':'On Ground Solid Storage Tanks',
'ISO33':'Elevated Liquid Storage Tanks',
'ISO34':'Elevated Solid Storage Tanks',
'ISO35':'Railroads (Track & Bed)',
'ISO36':'Highways',
'ISO37':'Runways',
'ISO38':'High Industrial Masonry Chimneys',
'ISO39':'High Industrial Concrete Chimneys',
'ISO40':'High Industrial Steel Chimneys',
'ISO41':'Cranes',
'ISO42':'Conveyor Systems',
'ISO43':'Conventional (< 100 ft.) Electrical Transmission Line Towers',
'ISO44':'Major (> 100 ft.) Electrical Transmission Line Towers',
'ISO45':'Broadcast Towers',
'ISO46':'Observation Towers',
'ISO47':'Offshore Towers',
'ISO48':'Canals',
'ISO49':'Earth Retaining Structures (> 20 ft. high)',
'ISO50':'Waterfront Structures',
'ISO51':'Residential Equipment',
'ISO52':'Office Equipment',
'ISO53':'Electrical Equipment',
'ISO54':'Mechanical Equipment',
'ISO55':'High Technology/Lab Equipment',
'ISO56':'Trains, Trucks, Airplanes'}


occupancy_code_mapping_dict = {
'ATC1':'Single Family Dwelling',
'ATC2':'Multi-Family Housing',
'ATC3':'Temporary Lodging',
'ATC4':'Group Institutional Housing',
'ATC5':'Retail Trade',
'ATC6':'Wholesale Trade',
'ATC7':'Personal and Repair Services',
'ATC8':'Professional, Technical and Business Services',
'ATC9':'Health Care Service',
'ATC10':'Entertainment and Recreation',
'ATC11':'Parking',
'ATC12':'Heavy Fabrication and Assembly',
'ATC13':'Light Fabrication and Assembly',
'ATC14':'Food and Drugs Processing',
'ATC15':'Chemicals Processing',
'ATC16':'Metal and Minerals Processing',
'ATC17':'High Technology',
'ATC18':'Construction',
'ATC19':'Petroleum',
'ATC20':'Agriculture',
'ATC21':'Mining',
'ATC22':'Religion and Nonprofit',
'ATC23':'General Services',
'ATC24':'Emergency Response Services',
'ATC25':'Education',
'ATC26':'Highway',
'ATC27':'Railroad',
'ATC28':'Air',
'ATC29':'Sea/Water',
'ATC30':'Electrical',
'ATC31':'Water',
'ATC32':'Sanitary Sewer',
'ATC33':'Natural Gas',
'ATC34':'Telephone & Telegraph',
'ATC35':'Communication (Radio & TV)',
'ATC36':'Flood Control',
'ATC37':'General Commercial',
'ATC38':'General Industrial',
'ATC39':'Misc.',
'ATC40':'Dwelling',
'ATC41':'Homeowner',
'ATC42':'MFD Homeowners Association',
'ATC43':'MFD Condomonium Unit Owner',
'ATC44':'Gasoline Service Station',
'ATC47':'Restaurants',
'ATC48':'Casinos',
'ATC49':'Acute Care Services Hospitals',
'ATC50':'OSHPD Acute Care Services Hospitals',
'ATC51':'Hotels - Large',
'ATC52':'Hotels - Small and Medium',
'ATC53':'Rental - General Commerical',
'ATC54':'Universities and Colleges',
'RMS IND26': 'Ports & Harbors',
'RMS IND16': 'Petrochemical – Pipelines',
'RMS IND1001':'HI Mining',
'RMS IND1011':'HI Cement',
'RMS IND1021':'HI Steel',
'RMS IND1031':'HI Pulp & Paper',
'RMS IND1041':'HI Glass',
'RMS IND1051':'HI General',
'RMS IND2001':'CP Primarily Outdoor',
'RMS IND2011':'CP Primarily Indoor',
'RMS IND3001':'LI Electronics',
'RMS IND3011':'LI Pharmaceutical',
'RMS IND3021':'LI Biomedical',
'RMS IND3031':'LI Semiconductor',
'RMS IND3041':'LI General Assembly',
'RMS IND3051':'LI General Manufacturing',
'RMS IND3061':'LI Technological Risks',
'RMS IND4001':'Petrochemical Refineries',
'RMS IND4011':'Petrochemical Pipelines',
'RMS IND4021':'Petrochemical Pipelines Below Ground',
'RMS IND4031':'Tank Farms',
'RMS IND5001':'EPG Fossil Fuel (Small)',
'RMS IND5002':'EPG Fossil Fuel (Medium)',
'RMS IND5003':'EPG Fossil Fuel (Large)',
'RMS IND5011':'EPG Hydroelectric',
'RMS IND5021':'EPG Co-Generation (Small)',
'RMS IND5022':'EPG Co-Generation (Medium)',
'RMS IND5023':'EPG Co-Generation (Large)',
'RMS IND5031':'EPG Gas Power (Small)',
'RMS IND5032':'EPG Gas Power (Medium)',
'RMS IND5033':'EPG Gas Power (Large)',
'RMS IND6001':'EP T&D Lines',
'RMS IND6011':'EP Substations (Small)',
'RMS IND6012':'EP Substations (Medium)',
'RMS IND6013':'EP Substations (Large)',
'RMS IND6021':'EP Nuclear Power Plant',
'RMS IND6031':'EP Wind Farms (Small)',
'RMS IND6032':'EP Wind Farms (Medium)',
'RMS IND6033':'EP Wind Farms (Large)',
'RMS IND6041':'EP Solar Farms (Small)',
'RMS IND7001':'Natural Gas',
'RMS IND7011':'Food & Beverage',
'RMS IND7021':'Data Processing/Telecommunications',
'RMS IND7031':'Communications',
'RMS IND7041':'Ports & Harbors',
'RMS IND7051':'Dams, Reservoirs only',
'RMS IND7061':'Water/Sewage Treatment Plants',
'RMS IND7071':'Mechanical',
'RMS IND6042':'EP Solar Farms (Mid)',
'RMS IND6043':'EP Solar Farms (Large)'}
